### ISSUE TITLE
baisse de la couverture de tests

### ISSUE THREAD

**Issue by e11137** [Mappy/fpm#7]
Tout est dans le titre :)

**Comment by bboyrankingz** [comment]
au contraire ? sauf le dernier commit ou c'est resté =

**Comment by e11137** [comment]
nop
https://coveralls.io/github/Mappy/fpm?branch=master
regarde le nombre de ligne couvertes au fil des commit

**Comment by Ignishky** [comment]
Mais bizaremment, quand tu reprends tous les commits 1 par 1, aucun ne fait baisser la couverture de code ...
